name: Run Appium Tests

on:
  push:
    branches:
      - main
jobs:
  appium-test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723
        options: --entrypoint=appium

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.*'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g appium
        appium --version

    - name: Create Android Emulator
      run: |
        echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
        $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-audio -no-window &

    - name: Start Appium Server
      run: |
        appium -p 4723 &
      shell: bash

    - name: Run Appium Tests
      run: |
        python -m unittest app/Tests/main_test.py
